
import { ProjectEntry, ProjectStatus } from "../types";

const ROADMAP_CSV = `MicroSaaS Name,Auth / Payments,Build Time (hrs),CTA Added,Category,Core Logic Built,Date,Day,Demo Video Recorded,Feedback Collected,Idea Finalized,MVP Completed,Notes / Learnings,Posted on Instagram,Posted on LinkedIn,Posted on X,Pricing Model,Prompt Designed,Revenue Generated,Scale Worthy,UI Ready,Users / Signups
LinkedIn post generator,,,,AI Writing & SEO,,"January 1, 2026",1,,,,,,,,,,,,,,
SEO blog outline generator,,,,AI Writing & SEO,,"January 2, 2026",2,,,,,,,,,,,,,,
YouTube video script generator,,,,AI Writing & SEO,,"January 3, 2026",3,,,,,,,,,,,,,,
AI email follow-up writer,,,,AI Writing & SEO,,"January 4, 2026",4,,,,,,,,,,,,,,
Cold email personalization tool,,,,AI Writing & SEO,,"January 5, 2026",5,,,,,,,,,,,,,,
Resume bullet-point improver,,,,AI Writing & SEO,,"January 7, 2026",7,,,,,,,,,,,,,,
Product description generator,,,,AI Writing & SEO,,"January 6, 2026",6,,,,,,,,,,,,,,
Job description optimizer,,,,AI Writing & SEO,,"January 8, 2026",8,,,,,,,,,,,,,,
Ad copy generator for Meta ads,,,,AI Writing & SEO,,"January 9, 2026",9,,,,,,,,,,,,,,
Twitter/X thread generator,,,,AI Writing & SEO,,"January 10, 2026",10,,,,,,,,,,,,,,
Instagram caption generator,,,,AI Writing & SEO,,"January 11, 2026",11,,,,,,,,,,,,,,
Blog content repurposer,,,,AI Writing & SEO,,"January 12, 2026",12,,,,,,,,,,,,,,
AI proofreading for legal tone,,,,AI Writing & SEO,,"January 13, 2026",13,,,,,,,,,,,,,,
Website homepage copy critic,,,,AI Writing & SEO,,"January 14, 2026",14,,,,,,,,,,,,,,
AI press release writer,,,,AI Writing & SEO,,"January 16, 2026",16,,,,,,,,,,,,,,
FAQ generator from website URL,,,,AI Writing & SEO,,"January 15, 2026",15,,,,,,,,,,,,,,
Newsletter subject-line optimizer,,,,AI Writing & SEO,,"January 17, 2026",17,,,,,,,,,,,,,,
SEO meta-title & description tool,,,,AI Writing & SEO,,"January 18, 2026",18,,,,,,,,,,,,,,
Medium article idea generator,,,,AI Writing & SEO,,"January 19, 2026",19,,,,,,,,,,,,,,
AI storytelling assistant,,,,AI Writing & SEO,,"January 20, 2026",20,,,,,,,,,,,,,,
Brand tone analyzer,,,,AI Writing & SEO,,"January 21, 2026",21,,,,,,,,,,,,,,
AI hook generator (Reels/Shorts),,,,AI Writing & SEO,,"January 22, 2026",22,,,,,,,,,,,,,,
Landing page hero-line generator,,,,AI Writing & SEO,,"January 24, 2026",24,,,,,,,,,,,,,,
Sales pitch deck text generator,,,,AI Writing & SEO,,"January 23, 2026",23,,,,,,,,,,,,,,
AI slogan & tagline generator,,,,AI Writing & SEO,,"January 25, 2026",25,,,,,,,,,,,,,,
Content plagiarism checker,,,,AI Writing & SEO,,"January 26, 2026",26,,,,,,,,,,,,,,
Grammar + tone fixer,,,,AI Writing & SEO,,"January 27, 2026",27,,,,,,,,,,,,,,
SEO content gap finder,,,,AI Writing & SEO,,"January 28, 2026",28,,,,,,,,,,,,,,
AI case study writer,,,,AI Writing & SEO,,"January 29, 2026",29,,,,,,,,,,,,,,
Email newsletter generator,,,,AI Writing & SEO,,"January 30, 2026",30,,,,,,,,,,,,,,
Monthly recap + bundle offer,,,,AI Writing & SEO,,"January 31, 2026",31,,,,,,,,,,,,,,
Instagram Reel idea generator,,,,Social Media Tools,,"February 1, 2026",32,,,,,,,,,,,,,,
Hashtag research microtool,,,,Social Media Tools,,"February 2, 2026",33,,,,,,,,,,,,,,
Social media content calendar generator,,,,Social Media Tools,,"February 3, 2026",34,,,,,,,,,,,,,,
Viral hook analyzer,,,,Social Media Tools,,"February 4, 2026",35,,,,,,,,,,,,,,
Reel caption + CTA generator,,,,Social Media Tools,,"February 6, 2026",37,,,,,,,,,,,,,,
Influencer DM outreach generator,,,,Social Media Tools,,"February 5, 2026",36,,,,,,,,,,,,,,
Comment reply AI for creators,,,,Social Media Tools,,"February 7, 2026",38,,,,,,,,,,,,,,
Instagram bio optimizer,,,,Social Media Tools,,"February 8, 2026",39,,,,,,,,,,,,,,
YouTube Shorts idea generator,,,,Social Media Tools,,"February 9, 2026",40,,,,,,,,,,,,,,
Trend-to-content converter,,,,Social Media Tools,,"February 10, 2026",41,,,,,,,,,,,,,,
AI meme caption generator,,,,Social Media Tools,,"February 11, 2026",42,,,,,,,,,,,,,,
Social post performance predictor,,,,Social Media Tools,,"February 12, 2026",43,,,,,,,,,,,,,,
LinkedIn carousel content generator,,,,Social Media Tools,,"February 13, 2026",44,,,,,,,,,,,,,,
Twitter/X engagement analyzer,,,,Social Media Tools,,"February 14, 2026",45,,,,,,,,,,,,,,
Brand voice consistency checker,,,,Social Media Tools,,"February 16, 2026",47,,,,,,,,,,,,,,
Social media audit tool,,,,Social Media Tools,,"February 15, 2026",46,,,,,,,,,,,,,,
Instagram Story poll ideas generator,,,,Social Media Tools,,"February 17, 2026",48,,,,,,,,,,,,,,
Creator posting time optimizer,,,,Social Media Tools,,"February 18, 2026",49,,,,,,,,,,,,,,
Influencer rate calculator,,,,Social Media Tools,,"February 19, 2026",50,,,,,,,,,,,,,,
AI community manager replies,,,,Social Media Tools,,"February 20, 2026",51,,,,,,,,,,,,,,
UGC content idea generator,,,,Social Media Tools,,"February 21, 2026",52,,,,,,,,,,,,,,
Reel script + shot list tool,,,,Social Media Tools,,"February 22, 2026",53,,,,,,,,,,,,,,
Social growth experiment tracker,,,,Social Media Tools,,"February 23, 2026",54,,,,,,,,,,,,,,
Personal brand positioning assistant,,,,Social Media Tools,,"February 24, 2026",55,,,,,,,,,,,,,,
AI content recycling engine,,,,Social Media Tools,,"February 25, 2026",56,,,,,,,,,,,,,,
Competitor analysis tool,,,,Social Media Tools,,"February 26, 2026",57,,,,,,,,,,,,,,
Video thumbnail analyzer,,,,Social Media Tools,,"February 27, 2026",58,,,,,,,,,,,,,,
AI CRM notes summarizer,,,,Sales CRM & Outreach,,"March 1, 2026",60,,,,,,,,,,,,,,
Creator media kit generator,,,,Social Media Tools,,"February 28, 2026",59,,,,,,,,,,,,,,
Lead qualification chatbot,,,,Sales CRM & Outreach,,"March 2, 2026",61,,,,,,,,,,,,,,
Cold call script generator,,,,Sales CRM & Outreach,,"March 3, 2026",62,,,,,,,,,,,,,,
Sales objection handler AI,,,,Sales CRM & Outreach,,"March 4, 2026",63,,,,,,,,,,,,,,
Proposal generator,,,,Sales CRM & Outreach,,"March 6, 2026",65,,,,,,,,,,,,,,
Follow-up reminder automation,,,,Sales CRM & Outreach,,"March 5, 2026",64,,,,,,,,,,,,,,
Discovery call question generator,,,,Sales CRM & Outreach,,"March 7, 2026",66,,,,,,,,,,,,,,
Deal probability predictor,,,,Sales CRM & Outreach,,"March 8, 2026",67,,,,,,,,,,,,,,
WhatsApp sales assistant,,,,Sales CRM & Outreach,,"March 9, 2026",68,,,,,,,,,,,,,,
Client onboarding checklist generator,,,,Sales CRM & Outreach,,"March 10, 2026",69,,,,,,,,,,,,,,
AI sales email analyzer,,,,Sales CRM & Outreach,,"March 11, 2026",70,,,,,,,,,,,,,,
Lead enrichment mini-tool,,,,Sales CRM & Outreach,,"March 12, 2026",71,,,,,,,,,,,,,,
Meeting recap to CRM updater,,,,Sales CRM & Outreach,,"March 13, 2026",72,,,,,,,,,,,,,,
Sales KPI tracker,,,,Sales CRM & Outreach,,"March 14, 2026",73,,,,,,,,,,,,,,
AI negotiation assistant,,,,Sales CRM & Outreach,,"March 15, 2026",74,,,,,,,,,,,,,,
Quote generator for freelancers,,,,Sales CRM & Outreach,,"March 16, 2026",75,,,,,,,,,,,,,,
Client churn risk detector,,,,Sales CRM & Outreach,,"March 17, 2026",76,,,,,,,,,,,,,,
Testimonial request generator,,,,Sales CRM & Outreach,,"March 18, 2026",77,,,,,,,,,,,,,,
AI upsell idea generator,,,,Sales CRM & Outreach,,"March 19, 2026",78,,,,,,,,,,,,,,
B2B lead scoring tool,,,,Sales CRM & Outreach,,"March 20, 2026",79,,,,,,,,,,,,,,
Sales funnel leak analyzer,,,,Sales CRM & Outreach,,"March 21, 2026",80,,,,,,,,,,,,,,
AI demo script writer,,,,Sales CRM & Outreach,,"March 22, 2026",81,,,,,,,,,,,,,,
CRM data cleaner,,,,Sales CRM & Outreach,,"March 24, 2026",83,,,,,,,,,,,,,,
Cold LinkedIn outreach writer,,,,Sales CRM & Outreach,,"March 23, 2026",82,,,,,,,,,,,,,,
AI sales coaching bot,,,,Sales CRM & Outreach,,"March 25, 2026",84,,,,,,,,,,,,,,
Referral email generator,,,,Sales CRM & Outreach,,"March 26, 2026",85,,,,,,,,,,,,,,
Pipeline health checker,,,,Sales CRM & Outreach,,"March 27, 2026",86,,,,,,,,,,,,,,
Sales territory mapper,,,,Sales CRM & Outreach,,"March 28, 2026",87,,,,,,,,,,,,,,
Commission calculator,,,,Sales CRM & Outreach,,"March 29, 2026",88,,,,,,,,,,,,,,
Closing technique recommender,,,,Sales CRM & Outreach,,"March 30, 2026",89,,,,,,,,,,,,,,
Solo Founder Sales Stack Launch,,,,Sales CRM & Outreach,,"March 31, 2026",90,,,,,,,,,,,,,,
Marketing funnel builder,,,,Marketing & Growth,,"April 1, 2026",91,,,,,,,,,,,,,,
AI ad creative analyzer,,,,Marketing & Growth,,"April 2, 2026",92,,,,,,,,,,,,,,
Campaign ROI calculator,,,,Marketing & Growth,,"April 3, 2026",93,,,,,,,,,,,,,,
Email drip campaign generator,,,,Marketing & Growth,,"April 4, 2026",94,,,,,,,,,,,,,,
Landing page conversion critic,,,,Marketing & Growth,,"April 6, 2026",96,,,,,,,,,,,,,,
Growth experiment tracker,,,,Marketing & Growth,,"April 5, 2026",95,,,,,,,,,,,,,,
AI A/B test idea generator,,,,Marketing & Growth,,"April 7, 2026",97,,,,,,,,,,,,,,
Referral program builder,,,,Marketing & Growth,,"April 8, 2026",98,,,,,,,,,,,,,,
Marketing KPI dashboard,,,,Marketing & Growth,,"April 9, 2026",99,,,,,,,,,,,,,,
Competitor ad spy tool,,,,Marketing & Growth,,"April 10, 2026",100,,,,,,,,,,,,,,
Content gap analyzer,,,,Marketing & Growth,,"April 11, 2026",101,,,,,,,,,,,,,,
Brand positioning canvas tool,,,,Marketing & Growth,,"April 12, 2026",102,,,,,,,,,,,,,,
AI buyer persona generator,,,,Marketing & Growth,,"April 13, 2026",103,,,,,,,,,,,,,,
Retargeting copy generator,,,,Marketing & Growth,,"April 14, 2026",104,,,,,,,,,,,,,,
SEO backlink outreach writer,,,,Marketing & Growth,,"April 15, 2026",105,,,,,,,,,,,,,,
Growth ideas generator,,,,Marketing & Growth,,"April 17, 2026",107,,,,,,,,,,,,,,
Campaign timeline planner,,,,Marketing & Growth,,"April 16, 2026",106,,,,,,,,,,,,,,
AI customer feedback analyzer,,,,Marketing & Growth,,"April 18, 2026",108,,,,,,,,,,,,,,
Marketing budget optimizer,,,,Marketing & Growth,,"April 20, 2026",110,,,,,,,,,,,,,,
Influencer campaign planner,,,,Marketing & Growth,,"April 19, 2026",109,,,,,,,,,,,,,,
Brand recall score predictor,,,,Marketing & Growth,,"April 21, 2026",111,,,,,,,,,,,,,,
Conversion copy heatmap analyzer,,,,Marketing & Growth,,"April 22, 2026",112,,,,,,,,,,,,,,
Marketing OKR tracker,,,,Marketing & Growth,,"April 23, 2026",113,,,,,,,,,,,,,,
AI PR outreach tool,,,,Marketing & Growth,,"April 24, 2026",114,,,,,,,,,,,,,,
Launch checklist generator,,,,Marketing & Growth,,"April 25, 2026",115,,,,,,,,,,,,,,
Event marketing planner,,,,Marketing & Growth,,"April 26, 2026",116,,,,,,,,,,,,,,
Lead magnet idea generator,,,,Marketing & Growth,,"April 28, 2026",118,,,,,,,,,,,,,,
Webinar script generator,,,,Marketing & Growth,,"April 27, 2026",117,,,,,,,,,,,,,,
Customer journey mapper,,,,Marketing & Growth,,"April 29, 2026",119,,,,,,,,,,,,,,
Marketing report generator,,,,Marketing & Growth,,"April 30, 2026",120,,,,,,,,,,,,,,
Startup idea validator,,,,Founder & Startup Tools,,"May 1, 2026",121,,,,,,,,,,,,,,
MVP feature prioritizer,,,,Founder & Startup Tools,,"May 2, 2026",122,,,,,,,,,,,,,,
Pitch deck generator,,,,Founder & Startup Tools,,"May 3, 2026",123,,,,,,,,,,,,,,
Investor email generator,,,,Founder & Startup Tools,,"May 4, 2026",124,,,,,,,,,,,,,,
AI co-founder simulator,,,,Founder & Startup Tools,,"May 6, 2026",126,,,,,,,,,,,,,,
Burn rate calculator,,,,Founder & Startup Tools,,"May 5, 2026",125,,,,,,,,,,,,,,
Startup legal checklist,,,,Founder & Startup Tools,,"May 7, 2026",127,,,,,,,,,,,,,,
Pricing strategy assistant,,,,Founder & Startup Tools,,"May 9, 2026",129,,,,,,,,,,,,,,
GTM strategy generator,,,,Founder & Startup Tools,,"May 8, 2026",128,,,,,,,,,,,,,,
Competitor SWOT analyzer,,,,Founder & Startup Tools,,"May 10, 2026",130,,,,,,,,,,,,,,
User persona builder,,,,Founder & Startup Tools,,"May 11, 2026",131,,,,,,,,,,,,,,
Customer interview question generator,,,,Founder & Startup Tools,,"May 12, 2026",132,,,,,,,,,,,,,,
Startup roadmap planner,,,,Founder & Startup Tools,,"May 13, 2026",133,,,,,,,,,,,,,,
SaaS metrics calculator,,,,Founder & Startup Tools,,"May 14, 2026",134,,,,,,,,,,,,,,
Feature request analyzer,,,,Founder & Startup Tools,,"May 16, 2026",136,,,,,,,,,,,,,,
Retention strategy generator,,,,Founder & Startup Tools,,"May 15, 2026",135,,,,,,,,,,,,,,
Startup risk assessment tool,,,,Founder & Startup Tools,,"May 17, 2026",137,,,,,,,,,,,,,,
Idea-market fit score tool,,,,Founder & Startup Tools,,"May 18, 2026",138,,,,,,,,,,,,,,
Churn reduction ideas tool,,,,Founder & Startup Tools,,"May 20, 2026",140,,,,,,,,,,,,,,
SaaS onboarding flow generator,,,,Founder & Startup Tools,,"May 19, 2026",139,,,,,,,,,,,,,,
Founder daily planner,,,,Founder & Startup Tools,,"May 21, 2026",141,,,,,,,,,,,,,,
Vision & mission generator,,,,Founder & Startup Tools,,"May 22, 2026",142,,,,,,,,,,,,,,
Startup storytelling assistant,,,,Founder & Startup Tools,,"May 23, 2026",143,,,,,,,,,,,,,,
Board update generator,,,,Founder & Startup Tools,,"May 24, 2026",144,,,,,,,,,,,,,,
Founder mental health tracker,,,,Founder & Startup Tools,,"May 25, 2026",145,,,,,,,,,,,,,,
Cap table modeler,,,,Founder & Startup Tools,,"May 26, 2026",146,,,,,,,,,,,,,,
Term sheet explainer,,,,Founder & Startup Tools,,"May 27, 2026",147,,,,,,,,,,,,,,
Exit strategy simulator,,,,Founder & Startup Tools,,"May 28, 2026",148,,,,,,,,,,,,,,
Startup glossary chatbot,,,,Founder & Startup Tools,,"May 29, 2026",149,,,,,,,,,,,,,,
Co-founder agreement generator,,,,Founder & Startup Tools,,"May 30, 2026",150,,,,,,,,,,,,,,
Startup-in-a-Box Launch,,,,Founder & Startup Tools,,"May 31, 2026",151,,,,,,,,,,,,,,
Resume screener AI,,,,HR Hiring & Recruitment,,"June 1, 2026",152,,,,,,,,,,,,,,
JD-to-resume matcher,,,,HR Hiring & Recruitment,,"June 2, 2026",153,,,,,,,,,,,,,,
Interview question generator,,,,HR Hiring & Recruitment,,"June 3, 2026",154,,,,,,,,,,,,,,
Candidate scorecard generator,,,,HR Hiring & Recruitment,,"June 4, 2026",155,,,,,,,,,,,,,,
AI rejection email writer,,,,HR Hiring & Recruitment,,"June 6, 2026",157,,,,,,,,,,,,,,
Hiring funnel tracker,,,,HR Hiring & Recruitment,,"June 5, 2026",156,,,,,,,,,,,,,,
Employee feedback analyzer,,,,HR Hiring & Recruitment,,"June 7, 2026",158,,,,,,,,,,,,,,
Performance review generator,,,,HR Hiring & Recruitment,,"June 8, 2026",159,,,,,,,,,,,,,,
AI onboarding assistant,,,,HR Hiring & Recruitment,,"June 10, 2026",161,,,,,,,,,,,,,,
HR policy generator,,,,HR Hiring & Recruitment,,"June 9, 2026",160,,,,,,,,,,,,,,
Skill gap analyzer,,,,HR Hiring & Recruitment,,"June 11, 2026",162,,,,,,,,,,,,,,
Payroll FAQ chatbot,,,,HR Hiring & Recruitment,,"June 12, 2026",163,,,,,,,,,,,,,,
Attrition predictor,,,,HR Hiring & Recruitment,,"June 13, 2026",164,,,,,,,,,,,,,,
Culture fit analyzer,,,,HR Hiring & Recruitment,,"June 14, 2026",165,,,,,,,,,,,,,,
Hiring bias detector,,,,HR Hiring & Recruitment,,"June 15, 2026",166,,,,,,,,,,,,,,
AI reference check assistant,,,,HR Hiring & Recruitment,,"June 16, 2026",167,,,,,,,,,,,,,,
Offer letter generator,,,,HR Hiring & Recruitment,,"June 17, 2026",168,,,,,,,,,,,,,,
Freelancer vetting tool,,,,HR Hiring & Recruitment,,"June 18, 2026",169,,,,,,,,,,,,,,
Team productivity analyzer,,,,HR Hiring & Recruitment,,"June 19, 2026",170,,,,,,,,,,,,,,
Internal job posting generator,,,,HR Hiring & Recruitment,,"June 21, 2026",172,,,,,,,,,,,,,,
HR compliance checklist,,,,HR Hiring & Recruitment,,"June 20, 2026",171,,,,,,,,,,,,,,
AI exit interview analyzer,,,,HR Hiring & Recruitment,,"June 22, 2026",173,,,,,,,,,,,,,,
Career path generator,,,,HR Hiring & Recruitment,,"June 23, 2026",174,,,,,,,,,,,,,,
HR chatbot for SMEs,,,,HR Hiring & Recruitment,,"June 24, 2026",175,,,,,,,,,,,,,,
Hiring cost calculator,,,,HR Hiring & Recruitment,,"June 25, 2026",176,,,,,,,,,,,,,,
Remote work policy generator,,,,HR Hiring & Recruitment,,"June 26, 2026",177,,,,,,,,,,,,,,
Employee perk selector,,,,HR Hiring & Recruitment,,"June 27, 2026",178,,,,,,,,,,,,,,
Team bonding idea generator,,,,HR Hiring & Recruitment,,"June 28, 2026",179,,,,,,,,,,,,,,
Diversity audit tool,,,,HR Hiring & Recruitment,,"June 29, 2026",180,,,,,,,,,,,,,,
Salary benchmarking tool,,,,HR Hiring & Recruitment,,"June 30, 2026",181,,,,,,,,,,,,,,
Invoice generator,,,,Finance & Accounting,,"July 1, 2026",182,,,,,,,,,,,,,,
Expense categorization AI,,,,Finance & Accounting,,"July 2, 2026",183,,,,,,,,,,,,,,
Budget planner,,,,Finance & Accounting,,"July 4, 2026",185,,,,,,,,,,,,,,
Cashflow predictor,,,,Finance & Accounting,,"July 3, 2026",184,,,,,,,,,,,,,,
Subscription tracking tool,,,,Finance & Accounting,,"July 5, 2026",186,,,,,,,,,,,,,,
Profit margin calculator,,,,Finance & Accounting,,"July 6, 2026",187,,,,,,,,,,,,,,
AI bookkeeping assistant,,,,Finance & Accounting,,"July 7, 2026",188,,,,,,,,,,,,,,
GST/tax reminder tool,,,,Finance & Accounting,,"July 8, 2026",189,,,,,,,,,,,,,,
Freelancer income tracker,,,,Finance & Accounting,,"July 9, 2026",190,,,,,,,,,,,,,,
Invoice follow-up automation,,,,Finance & Accounting,,"July 10, 2026",191,,,,,,,,,,,,,,
Financial report summarizer,,,,Finance & Accounting,,"July 11, 2026",192,,,,,,,,,,,,,,
SaaS MRR calculator,,,,Finance & Accounting,,"July 13, 2026",194,,,,,,,,,,,,,,
Pricing margin simulator,,,,Finance & Accounting,,"July 12, 2026",193,,,,,,,,,,,,,,
Late payment risk detector,,,,Finance & Accounting,,"July 14, 2026",195,,,,,,,,,,,,,,
AI audit checklist,,,,Finance & Accounting,,"July 15, 2026",196,,,,,,,,,,,,,,
Financial health score tool,,,,Finance & Accounting,,"July 16, 2026",197,,,,,,,,,,,,,,
Revenue forecasting tool,,,,Finance & Accounting,,"July 17, 2026",198,,,,,,,,,,,,,,
AI CFO assistant,,,,Finance & Accounting,,"July 19, 2026",200,,,,,,,,,,,,,,
Cost optimization analyzer,,,,Finance & Accounting,,"July 18, 2026",199,,,,,,,,,,,,,,
Tax-saving ideas generator,,,,Finance & Accounting,,"July 20, 2026",201,,,,,,,,,,,,,,
Financial goal tracker,,,,Finance & Accounting,,"July 21, 2026",202,,,,,,,,,,,,,,
Vendor payment tracker,,,,Finance & Accounting,,"July 22, 2026",203,,,,,,,,,,,,,,
Financial anomaly detector,,,,Finance & Accounting,,"July 23, 2026",204,,,,,,,,,,,,,,
Expense fraud detector,,,,Finance & Accounting,,"July 24, 2026",205,,,,,,,,,,,,,,
Crypto tax estimator,,,,Finance & Accounting,,"July 26, 2026",207,,,,,,,,,,,,,,
Monthly finance dashboard,,,,Finance & Accounting,,"July 25, 2026",206,,,,,,,,,,,,,,
Runway calculator,,,,Finance & Accounting,,"July 27, 2026",208,,,,,,,,,,,,,,
Unit economics modeler,,,,Finance & Accounting,,"July 28, 2026",209,,,,,,,,,,,,,,
Debt payoff planner,,,,Finance & Accounting,,"July 30, 2026",211,,,,,,,,,,,,,,
Investment portfolio tracker,,,,Finance & Accounting,,"July 29, 2026",210,,,,,,,,,,,,,,
Finance Bundle Launch,,,,Finance & Accounting,,"July 31, 2026",212,,,,,,,,,,,,,,
Contract summarizer,,,,Legal & Compliance,,"August 1, 2026",213,,,,,,,,,,,,,,
NDA generator,,,,Legal & Compliance,,"August 2, 2026",214,,,,,,,,,,,,,,
Privacy policy generator,,,,Legal & Compliance,,"August 3, 2026",215,,,,,,,,,,,,,,
Terms & conditions generator,,,,Legal & Compliance,,"August 4, 2026",216,,,,,,,,,,,,,,
Contract clause explainer,,,,Legal & Compliance,,"August 6, 2026",218,,,,,,,,,,,,,,
Legal risk analyzer,,,,Legal & Compliance,,"August 5, 2026",217,,,,,,,,,,,,,,
AI compliance checklist,,,,Legal & Compliance,,"August 7, 2026",219,,,,,,,,,,,,,,
Startup legal roadmap,,,,Legal & Compliance,,"August 8, 2026",220,,,,,,,,,,,,,,
IP protection checklist,,,,Legal & Compliance,,"August 10, 2026",222,,,,,,,,,,,,,,
Employment contract generator,,,,Legal & Compliance,,"August 9, 2026",221,,,,,,,,,,,,,,
Legal document classifier,,,,Legal & Compliance,,"August 11, 2026",223,,,,,,,,,,,,,,
Case law summarizer,,,,Legal & Compliance,,"August 12, 2026",224,,,,,,,,,,,,,,
Regulatory update notifier,,,,Legal & Compliance,,"August 13, 2026",225,,,,,,,,,,,,,,
Vendor contract analyzer,,,,Legal & Compliance,,"August 14, 2026",226,,,,,,,,,,,,,,
AI legal due diligence,,,,Legal & Compliance,,"August 16, 2026",228,,,,,,,,,,,,,,
Legal chatbot for SMEs,,,,Legal & Compliance,,"August 15, 2026",227,,,,,,,,,,,,,,
Data protection compliance tool,,,,Legal & Compliance,,"August 17, 2026",229,,,,,,,,,,,,,,
Arbitration clause checker,,,,Legal & Compliance,,"August 19, 2026",231,,,,,,,,,,,,,,
Legal notice generator,,,,Legal & Compliance,,"August 18, 2026",230,,,,,,,,,,,,,,
SaaS compliance tracker,,,,Legal & Compliance,,"August 20, 2026",232,,,,,,,,,,,,,,
Agreement comparison tool,,,,Legal & Compliance,,"August 21, 2026",233,,,,,,,,,,,,,,
Legal workflow automation,,,,Legal & Compliance,,"August 23, 2026",235,,,,,,,,,,,,,,
Legal cost estimator,,,,Legal & Compliance,,"August 22, 2026",234,,,,,,,,,,,,,,
AI paralegal assistant,,,,Legal & Compliance,,"August 24, 2026",236,,,,,,,,,,,,,,
Legal knowledge base builder,,,,Legal & Compliance,,"August 25, 2026",237,,,,,,,,,,,,,,
Patent search assistant,,,,Legal & Compliance,,"August 26, 2026",238,,,,,,,,,,,,,,
Trademark availability checker,,,,Legal & Compliance,,"August 27, 2026",239,,,,,,,,,,,,,,
Legal jargon simplifier,,,,Legal & Compliance,,"August 28, 2026",240,,,,,,,,,,,,,,
Dispute resolution bot,,,,Legal & Compliance,,"August 29, 2026",241,,,,,,,,,,,,,,
Consultancy agreement generator,,,,Legal & Compliance,,"August 30, 2026",242,,,,,,,,,,,,,,
Legal Tech Toolkit Launch,,,,Legal & Compliance,,"August 31, 2026",243,,,,,,,,,,,,,,
AI tutor chatbot,,,,Education & Learning,,"September 1, 2026",244,,,,,,,,,,,,,,
Personalized study planner,,,,Education & Learning,,"September 2, 2026",245,,,,,,,,,,,,,,
Flashcard generator,,,,Education & Learning,,"September 3, 2026",246,,,,,,,,,,,,,,
Course outline generator,,,,Education & Learning,,"September 5, 2026",248,,,,,,,,,,,,,,
Quiz generator,,,,Education & Learning,,"September 4, 2026",247,,,,,,,,,,,,,,
Doubt-solving assistant,,,,Education & Learning,,"September 6, 2026",249,,,,,,,,,,,,,,
Exam revision planner,,,,Education & Learning,,"September 7, 2026",250,,,,,,,,,,,,,,
Learning progress tracker,,,,Education & Learning,,"September 8, 2026",251,,,,,,,,,,,,,,
AI homework helper,,,,Education & Learning,,"September 9, 2026",252,,,,,,,,,,,,,,
Language learning chatbot,,,,Education & Learning,,"September 10, 2026",253,,,,,,,,,,,,,,
Teacher lesson planner,,,,Education & Learning,,"September 11, 2026",254,,,,,,,,,,,,,,
Student feedback analyzer,,,,Education & Learning,,"September 12, 2026",255,,,,,,,,,,,,,,
AI note summarizer,,,,Education & Learning,,"September 13, 2026",256,,,,,,,,,,,,,,
Career guidance assistant,,,,Education & Learning,,"September 14, 2026",257,,,,,,,,,,,,,,
Skill roadmap generator,,,,Education & Learning,,"September 15, 2026",258,,,,,,,,,,,,,,
Learning habit tracker,,,,Education & Learning,,"September 16, 2026",259,,,,,,,,,,,,,,
AI mock interview tool,,,,Education & Learning,,"September 17, 2026",260,,,,,,,,,,,,,,
Online course idea validator,,,,Education & Learning,,"September 18, 2026",261,,,,,,,,,,,,,,
Certification prep planner,,,,Education & Learning,,"September 19, 2026",262,,,,,,,,,,,,,,
Microlearning content generator,,,,Education & Learning,,"September 20, 2026",263,,,,,,,,,,,,,,
AI reading companion,,,,Education & Learning,,"September 21, 2026",264,,,,,,,,,,,,,,
Classroom engagement analyzer,,,,Education & Learning,,"September 22, 2026",265,,,,,,,,,,,,,,
Learning analytics dashboard,,,,Education & Learning,,"September 24, 2026",267,,,,,,,,,,,,,,
Parent-teacher communication bot,,,,Education & Learning,,"September 23, 2026",266,,,,,,,,,,,,,,
AI exam paper generator,,,,Education & Learning,,"September 25, 2026",268,,,,,,,,,,,,,,
Bibliograhpy generator,,,,Education & Learning,,"September 26, 2026",269,,,,,,,,,,,,,,
Plagiarism checker for students,,,,Education & Learning,,"September 27, 2026",270,,,,,,,,,,,,,,
Group project manager,,,,Education & Learning,,"September 28, 2026",271,,,,,,,,,,,,,,
Essay structure builder,,,,Education & Learning,,"September 29, 2026",272,,,,,,,,,,,,,,
AI diet planner,,,,Health Fitness & Wellness,,"October 1, 2026",274,,,,,,,,,,,,,,
Education Bundle Launch,,,,Education & Learning,,"September 30, 2026",273,,,,,,,,,,,,,,
Workout plan generator,,,,Health Fitness & Wellness,,"October 2, 2026",275,,,,,,,,,,,,,,
Mental health journaling bot,,,,Health Fitness & Wellness,,"October 4, 2026",277,,,,,,,,,,,,,,
Habit tracker,,,,Health Fitness & Wellness,,"October 3, 2026",276,,,,,,,,,,,,,,
Sleep improvement assistant,,,,Health Fitness & Wellness,,"October 5, 2026",278,,,,,,,,,,,,,,
Fitness progress analyzer,,,,Health Fitness & Wellness,,"October 6, 2026",279,,,,,,,,,,,,,,
AI calorie tracker,,,,Health Fitness & Wellness,,"October 7, 2026",280,,,,,,,,,,,,,,
Stress management chatbot,,,,Health Fitness & Wellness,,"October 8, 2026",281,,,,,,,,,,,,,,
Meditation planner,,,,Health Fitness & Wellness,,"October 9, 2026",282,,,,,,,,,,,,,,
Health goal tracker,,,,Health Fitness & Wellness,,"October 10, 2026",283,,,,,,,,,,,,,,
AI symptom checker,,,,Health Fitness & Wellness,,"October 11, 2026",284,,,,,,,,,,,,,,
Personal wellness dashboard,,,,Health Fitness & Wellness,,"October 12, 2026",285,,,,,,,,,,,,,,
Nutrition label analyzer,,,,Health Fitness & Wellness,,"October 13, 2026",286,,,,,,,,,,,,,,
Workout form explainer,,,,Health Fitness & Wellness,,"October 14, 2026",287,,,,,,,,,,,,,,
Recovery & rest planner,,,,Health Fitness & Wellness,,"October 15, 2026",288,,,,,,,,,,,,,,
Corporate wellness tracker,,,,Health Fitness & Wellness,,"October 16, 2026",289,,,,,,,,,,,,,,
Health reminder automation,,,,Health Fitness & Wellness,,"October 17, 2026",290,,,,,,,,,,,,,,
AI health coach,,,,Health Fitness & Wellness,,"October 18, 2026",291,,,,,,,,,,,,,,
Period tracking assistant,,,,Health Fitness & Wellness,,"October 19, 2026",292,,,,,,,,,,,,,,
Fitness community manager,,,,Health Fitness & Wellness,,"October 20, 2026",293,,,,,,,,,,,,,,
Wellness content generator,,,,Health Fitness & Wellness,,"October 21, 2026",294,,,,,,,,,,,,,,
Health risk predictor,,,,Health Fitness & Wellness,,"October 22, 2026",295,,,,,,,,,,,,,,
Telehealth triage bot,,,,Health Fitness & Wellness,,"October 23, 2026",296,,,,,,,,,,,,,,
Fitness challenge generator,,,,Health Fitness & Wellness,,"October 24, 2026",297,,,,,,,,,,,,,,
Health habit nudger,,,,Health Fitness & Wellness,,"October 25, 2026",298,,,,,,,,,,,,,,
Water intake tracker,,,,Health Fitness & Wellness,,"October 26, 2026",299,,,,,,,,,,,,,,
Step count analyzer,,,,Health Fitness & Wellness,,"October 27, 2026",300,,,,,,,,,,,,,,
Running route planner,,,,Health Fitness & Wellness,,"October 28, 2026",301,,,,,,,,,,,,,,
Yoga pose corrector,,,,Health Fitness & Wellness,,"October 29, 2026",302,,,,,,,,,,,,,,
Health Tech Launch,,,,Health Fitness & Wellness,,"October 31, 2026",304,,,,,,,,,,,,,,
Macro calculator,,,,Health Fitness & Wellness,,"October 30, 2026",303,,,,,,,,,,,,,,
Product description optimizer,,,,E-commerce & Retail,,"November 1, 2026",305,,,,,,,,,,,,,,
Review sentiment analyzer,,,,E-commerce & Retail,,"November 2, 2026",306,,,,,,,,,,,,,,
Pricing comparison tool,,,,E-commerce & Retail,,"November 3, 2026",307,,,,,,,,,,,,,,
Inventory forecasting AI,,,,E-commerce & Retail,,"November 4, 2026",308,,,,,,,,,,,,,,
Cart abandonment email generator,,,,E-commerce & Retail,,"November 5, 2026",309,,,,,,,,,,,,,,
Competitor price tracker,,,,E-commerce & Retail,,"November 7, 2026",311,,,,,,,,,,,,,,
Product recommendation engine,,,,E-commerce & Retail,,"November 6, 2026",310,,,,,,,,,,,,,,
AI upsell suggestions,,,,E-commerce & Retail,,"November 8, 2026",312,,,,,,,,,,,,,,
Shopify SEO optimizer,,,,E-commerce & Retail,,"November 9, 2026",313,,,,,,,,,,,,,,
Customer support chatbot,,,,E-commerce & Retail,,"November 10, 2026",314,,,,,,,,,,,,,,
Return reason analyzer,,,,E-commerce & Retail,,"November 12, 2026",316,,,,,,,,,,,,,,
Order delay notifier,,,,E-commerce & Retail,,"November 11, 2026",315,,,,,,,,,,,,,,
Demand prediction tool,,,,E-commerce & Retail,,"November 13, 2026",317,,,,,,,,,,,,,,
AI merchandising assistant,,,,E-commerce & Retail,,"November 14, 2026",318,,,,,,,,,,,,,,
Vendor performance tracker,,,,E-commerce & Retail,,"November 15, 2026",319,,,,,,,,,,,,,,
Customer lifetime value calculator,,,,E-commerce & Retail,,"November 16, 2026",320,,,,,,,,,,,,,,
AI image alt-text generator,,,,E-commerce & Retail,,"November 18, 2026",322,,,,,,,,,,,,,,
Ecommerce analytics dashboard,,,,E-commerce & Retail,,"November 17, 2026",321,,,,,,,,,,,,,,
Discount strategy optimizer,,,,E-commerce & Retail,,"November 19, 2026",323,,,,,,,,,,,,,,
Product launch checklist,,,,E-commerce & Retail,,"November 20, 2026",324,,,,,,,,,,,,,,
AI loyalty program builder,,,,E-commerce & Retail,,"November 22, 2026",326,,,,,,,,,,,,,,
Ecommerce fraud detector,,,,E-commerce & Retail,,"November 21, 2026",325,,,,,,,,,,,,,,
Store conversion optimizer,,,,E-commerce & Retail,,"November 23, 2026",327,,,,,,,,,,,,,,
Product bundling tool,,,,E-commerce & Retail,,"November 24, 2026",328,,,,,,,,,,,,,,
Ecommerce growth ideas engine,,,,E-commerce & Retail,,"November 25, 2026",329,,,,,,,,,,,,,,
Dropshipping product finder,,,,E-commerce & Retail,,"November 26, 2026",330,,,,,,,,,,,,,,
Packaging design feedback,,,,E-commerce & Retail,,"November 27, 2026",331,,,,,,,,,,,,,,
Shipping cost calculator,,,,E-commerce & Retail,,"November 28, 2026",332,,,,,,,,,,,,,,
E-com Holiday Bundle Launch,,,,E-commerce & Retail,,"November 30, 2026",334,,,,,,,,,,,,,,
Review response generator,,,,E-commerce & Retail,,"November 29, 2026",333,,,,,,,,,,,,,,
AI task prioritizer,,,,Operations & Personal Brand,,"December 1, 2026",335,,,,,,,,,,,,,,
Meeting agenda generator,,,,Operations & Personal Brand,,"December 2, 2026",336,,,,,,,,,,,,,,
Meeting minutes summarizer,,,,Operations & Personal Brand,,"December 3, 2026",337,,,,,,,,,,,,,,
SOP generator,,,,Operations & Personal Brand,,"December 4, 2026",338,,,,,,,,,,,,,,
Workflow automation builder,,,,Operations & Personal Brand,,"December 5, 2026",339,,,,,,,,,,,,,,
Internal wiki generator,,,,Operations & Personal Brand,,"December 6, 2026",340,,,,,,,,,,,,,,
Productivity analytics tool,,,,Operations & Personal Brand,,"December 7, 2026",341,,,,,,,,,,,,,,
AI decision assistant,,,,Operations & Personal Brand,,"December 8, 2026",342,,,,,,,,,,,,,,
Focus & distraction tracker,,,,Operations & Personal Brand,,"December 10, 2026",344,,,,,,,,,,,,,,
Time tracking analyzer,,,,Operations & Personal Brand,,"December 9, 2026",343,,,,,,,,,,,,,,
Daily planning assistant,,,,Operations & Personal Brand,,"December 11, 2026",345,,,,,,,,,,,,,,
Team workload balancer,,,,Operations & Personal Brand,,"December 12, 2026",346,,,,,,,,,,,,,,
OKR tracking tool,,,,Operations & Personal Brand,,"December 13, 2026",347,,,,,,,,,,,,,,
AI process optimizer,,,,Operations & Personal Brand,,"December 14, 2026",348,,,,,,,,,,,,,,
Internal chatbot,,,,Operations & Personal Brand,,"December 15, 2026",349,,,,,,,,,,,,,,
Bottleneck detection tool,,,,Operations & Personal Brand,,"December 17, 2026",351,,,,,,,,,,,,,,
Knowledge base search AI,,,,Operations & Personal Brand,,"December 16, 2026",350,,,,,,,,,,,,,,
Productivity score calculator,,,,Operations & Personal Brand,,"December 19, 2026",353,,,,,,,,,,,,,,
Capacity planning assistant,,,,Operations & Personal Brand,,"December 18, 2026",352,,,,,,,,,,,,,,
Automation ROI calculator,,,,Operations & Personal Brand,,"December 20, 2026",354,,,,,,,,,,,,,,
Remote work productivity tracker,,,,Operations & Personal Brand,,"December 22, 2026",356,,,,,,,,,,,,,,
Internal audit checklist tool,,,,Operations & Personal Brand,,"December 21, 2026",355,,,,,,,,,,,,,,
Decision log generator,,,,Operations & Personal Brand,,"December 23, 2026",357,,,,,,,,,,,,,,
AI retrospective facilitator,,,,Operations & Personal Brand,,"December 24, 2026",358,,,,,,,,,,,,,,
Prompt management tool,,,,Operations & Personal Brand,,"December 26, 2026",360,,,,,,,,,,,,,,
Operations dashboard,,,,Operations & Personal Brand,,"December 25, 2026",359,,,,,,,,,,,,,,
API tester mini-tool,,,,Operations & Personal Brand,,"December 27, 2026",361,,,,,,,,,,,,,,
AI workflow builder,,,,Operations & Personal Brand,,"December 28, 2026",362,,,,,,,,,,,,,,
Personal brand audit tool,,,,Operations & Personal Brand,,"December 29, 2026",363,,,,,,,,,,,,,,
Year End Master Bundle Launch,,,,Operations & Personal Brand,,"December 31, 2026",365,,,,,,,,,,,,,,
Content idea generator,,,,Operations & Personal Brand,,"December 30, 2026",364,,,,,,,,,,,,,,`;

const monthsMap: Record<string, string> = {
  "January": "01", "February": "02", "March": "03", "April": "04",
  "May": "05", "June": "06", "July": "07", "August": "08",
  "September": "09", "October": "10", "November": "11", "December": "12"
};

export function parseRoadmapCsv(): Record<string, ProjectEntry> {
  const lines = ROADMAP_CSV.split('\n');
  const projects: Record<string, ProjectEntry> = {};

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    // Use a regex that respects quoted strings containing commas
    const parts = line.match(/(".*?"|[^,]+|(?<=,)(?=,)|(?<=,)$|^$)/g);
    if (!parts) continue;

    const name = parts[0]?.replace(/"/g, '').trim();
    const auth = parts[1]?.replace(/"/g, '').trim();
    const buildTime = parseFloat(parts[2]?.replace(/"/g, '') || '0');
    const cta = parts[3]?.toLowerCase() === 'true' || parts[3] === '1';
    const category = parts[4]?.replace(/"/g, '').trim();
    const coreLogic = parts[5]?.toLowerCase() === 'true' || parts[5] === '1';
    const dateStr = parts[6]?.replace(/"/g, '').trim();
    const dayNumber = parseInt(parts[7]?.replace(/"/g, '') || '0');
    const video = parts[8]?.toLowerCase() === 'true' || parts[8] === '1';
    const feedback = parts[9]?.toLowerCase() === 'true' || parts[9] === '1';
    const ideaFinal = parts[10]?.toLowerCase() === 'true' || parts[10] === '1';
    const mvp = parts[11]?.toLowerCase() === 'true' || parts[11] === '1';
    const notes = parts[12]?.replace(/"/g, '').trim();
    const ig = parts[13]?.toLowerCase() === 'true' || parts[13] === '1';
    const li = parts[14]?.toLowerCase() === 'true' || parts[14] === '1';
    const x = parts[15]?.toLowerCase() === 'true' || parts[15] === '1';
    const pricing = parts[16]?.replace(/"/g, '').trim();
    const prompt = parts[17]?.toLowerCase() === 'true' || parts[17] === '1';
    const revenue = parseFloat(parts[18]?.replace(/"/g, '') || '0');
    const scale = parts[19]?.toLowerCase() === 'true' || parts[19] === '1';
    const ui = parts[20]?.toLowerCase() === 'true' || parts[20] === '1';
    const users = parseFloat(parts[21]?.replace(/"/g, '') || '0');

    if (name && dateStr) {
      const dateParts = dateStr.split(' ');
      const monthName = dateParts[0];
      const dayNum = dateParts[1]?.replace(',', '').padStart(2, '0');
      const yearNum = dateParts[2];
      const monthNum = monthsMap[monthName];

      if (monthNum && dayNum && yearNum) {
        const id = `${yearNum}-${monthNum}-${dayNum}`;
        projects[id] = {
          id,
          title: name,
          description: `Planned as part of the ${category} category. Day ${dayNumber} of the 365-day challenge.`,
          status: ProjectStatus.PLANNED,
          techStack: [],
          tags: category ? [category] : [],
          notes: notes || '',
          authPayments: auth,
          buildTime,
          ctaAdded: cta,
          category,
          coreLogicBuilt: coreLogic,
          demoVideoRecorded: video,
          feedbackCollected: feedback,
          ideaFinalized: ideaFinal,
          mvpCompleted: mvp,
          postedInstagram: ig,
          postedLinkedIn: li,
          postedX: x,
          pricingModel: pricing,
          promptDesigned: prompt,
          revenueGenerated: revenue,
          scaleWorthy: scale,
          uiReady: ui,
          usersSignups: users,
          dayNumber
        };
      }
    }
  }

  return projects;
}
